### ISSUE TITLE
Is it compatable with react-router?

### ISSUE THREAD

**Issue by endigo** [garth/material-components#5]
How to use AppBar with Link?

**Comment by garth** [comment]
@ENDiGo Good question. Of course it should work with any external components, you'll just need to style them yourself.

The real issue here is weather react-router and `Link` are the right way to go? material-components have been designed for pure UI rendering (no state or non-ui logic in the view components), which react-router is not, since it embeds logic and data of your routing inside your view components.

Instead I would suggest to look at pure alternatives such as [url-mapper](https://github.com/cerebral/url-mapper) and [addressbar](https://github.com/cerebral/addressbar), these are both used by cerebral, but can be used by any framework to create pure UI components.
